build:
  image: default-bionic
  environment:
    timezone: "Asia/Tokyo"
  dependencies:
    before:
      # install composer
      - wget https://raw.githubusercontent.com/composer/getcomposer.org/dadb501680566074a956f0a52f8e87a3612b0eae/web/installer -O - -q | php -- --quiet

      # install phive
      - wget -O phive.phar "https://phar.io/releases/phive.phar"
      - wget -O phive.phar.asc "https://phar.io/releases/phive.phar.asc"
      - gpg --keyserver hkps://keys.openpgp.org --recv-keys 0x6AF725270AB81E04D79442549D8A98B29B2D5D79
      - gpg --verify phive.phar.asc phive.phar
      - rm phive.phar.asc
      - chmod +x phive.phar
      - mv phive.phar ./tools/phive

      # install phars
      - ./tools/phive --no-progress --home ./.phive install --trust-gpg-keys E82B2FB314E9906E,12CE0F1D262429A5,2DF45277AEF09A2F --force-accept-unsigned
  tests:
    override:
      - command: ./composer.phar test -- --coverage-clover=clover.xml
        coverage:
          file: clover.xml
          format: php-clover
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run
          - php-scrutinizer-run

          - command: ./tools/psalm --report=checkstyle-psalm.xml
            analysis:
              file: checkstyle-psalm.xml
              format: "general-checkstyle"

          - store-in-cache repository "php-cs-fixer" .php-cs-fixer.cache
          - restore-from-cache repository "php-cs-fixer"
          - exists-in-cache repository "php-cs-fixer"

          - command: ./tools/php-cs-fixer fix --dry-run --format=checkstyle . > checkstyle-php-cs-fixer.xml
            analysis:
              file: checkstyle-php-cs-fixer.xml
              format: "general-checkstyle"

filter:
  excluded_paths:
    - "http-client-benchmark/"
    - "sample-app/"
