name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: "Cache tools installed with PHIVE"
        uses: "actions/cache@v3"
        with:
          path: "${{ runner.temp }}/.phive"
          key: "php-${{ matrix.php-version }}-phive-${{ hashFiles('.phive/phars.xml') }}"
          restore-keys: "php-${{ matrix.php-version }}-phive-"

      - name: "Install PHIVE"
        uses: "szepeviktor/phive@v1"
        with:
          home: "${{ runner.temp }}/.phive"
          binPath: "${{ github.workspace }}/tools/phive"

      - name: "Install PHP tools with PHIVE"
        uses: "szepeviktor/phive-install@v1"
        with:
          home: "${{ runner.temp }}/.phive"
          binPath: "${{ github.workspace }}/tools/phive"
          trustGpgKeys: "E82B2FB314E9906E,12CE0F1D262429A5,2DF45277AEF09A2F"

      - name: Build phar archive
        run: composer build

      - uses: actions/upload-artifact@v3
        with:
          name: heavyrain.phar
          path: bin/heavyrain.phar

      # TODO: create_release using actions/create-release@v1 and actions/upload-release-asset@v1
